 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/headlines", type: :request do
  # Headline. As you add validations to Headline, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Headline.create! valid_attributes
      get headlines_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      headline = Headline.create! valid_attributes
      get headline_url(headline)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_headline_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      headline = Headline.create! valid_attributes
      get edit_headline_url(headline)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Headline" do
        expect {
          post headlines_url, params: { headline: valid_attributes }
        }.to change(Headline, :count).by(1)
      end

      it "redirects to the created headline" do
        post headlines_url, params: { headline: valid_attributes }
        expect(response).to redirect_to(headline_url(Headline.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Headline" do
        expect {
          post headlines_url, params: { headline: invalid_attributes }
        }.to change(Headline, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post headlines_url, params: { headline: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested headline" do
        headline = Headline.create! valid_attributes
        patch headline_url(headline), params: { headline: new_attributes }
        headline.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the headline" do
        headline = Headline.create! valid_attributes
        patch headline_url(headline), params: { headline: new_attributes }
        headline.reload
        expect(response).to redirect_to(headline_url(headline))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        headline = Headline.create! valid_attributes
        patch headline_url(headline), params: { headline: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested headline" do
      headline = Headline.create! valid_attributes
      expect {
        delete headline_url(headline)
      }.to change(Headline, :count).by(-1)
    end

    it "redirects to the headlines list" do
      headline = Headline.create! valid_attributes
      delete headline_url(headline)
      expect(response).to redirect_to(headlines_url)
    end
  end
end
